name: Update from origin
on: 
  push:
    branches-ignore:
      - devel
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          owner: ledgerwatch
          base: devel
          head: devel
          merge_method: merge
          pr_message: Sync fork with original repository
          pr_title: Update from origin
          token: ${{ secrets.CI_TOKEN }}
          ignore_fail: true # to just have a PR
